//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC3.SLMap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SLMap.ISLMap")]
    public interface ISLMap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMap/GetMap", ReplyAction="http://tempuri.org/ISLMap/GetMapResponse")]
        DomainModel.Map GetMap(int id, ref string[] errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMap/InsertMap", ReplyAction="http://tempuri.org/ISLMap/InsertMapResponse")]
        void InsertMap(DomainModel.Map map, ref string[] errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMap/UpdateMap", ReplyAction="http://tempuri.org/ISLMap/UpdateMapResponse")]
        void UpdateMap(DomainModel.Map map, ref string[] errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMap/DeleteMap", ReplyAction="http://tempuri.org/ISLMap/DeleteMapResponse")]
        void DeleteMap(int id, ref string[] errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMap/GetMapList", ReplyAction="http://tempuri.org/ISLMap/GetMapListResponse")]
        DomainModel.Map[] GetMapList(ref string[] errors);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISLMapChannel : MVC3.SLMap.ISLMap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SLMapClient : System.ServiceModel.ClientBase<MVC3.SLMap.ISLMap>, MVC3.SLMap.ISLMap {
        
        public SLMapClient() {
        }
        
        public SLMapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SLMapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLMapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLMapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DomainModel.Map GetMap(int id, ref string[] errors) {
            return base.Channel.GetMap(id, ref errors);
        }
        
        public void InsertMap(DomainModel.Map map, ref string[] errors) {
            base.Channel.InsertMap(map, ref errors);
        }
        
        public void UpdateMap(DomainModel.Map map, ref string[] errors) {
            base.Channel.UpdateMap(map, ref errors);
        }
        
        public void DeleteMap(int id, ref string[] errors) {
            base.Channel.DeleteMap(id, ref errors);
        }
        
        public DomainModel.Map[] GetMapList(ref string[] errors) {
            return base.Channel.GetMapList(ref errors);
        }
    }
}
