//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC3.SLLeague {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SLLeague.ISLLeague")]
    public interface ISLLeague {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLLeague/GetLeague", ReplyAction="http://tempuri.org/ISLLeague/GetLeagueResponse")]
        DomainModel.League GetLeague(int id, ref string[] errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLLeague/InsertLeague", ReplyAction="http://tempuri.org/ISLLeague/InsertLeagueResponse")]
        void InsertLeague(DomainModel.League league, ref string[] errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLLeague/UpdateLeague", ReplyAction="http://tempuri.org/ISLLeague/UpdateLeagueResponse")]
        void UpdateLeague(DomainModel.League league, ref string[] errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLLeague/DeleteLeague", ReplyAction="http://tempuri.org/ISLLeague/DeleteLeagueResponse")]
        void DeleteLeague(int id, ref string[] errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLLeague/GetLeagueList", ReplyAction="http://tempuri.org/ISLLeague/GetLeagueListResponse")]
        DomainModel.League[] GetLeagueList(ref string[] errors);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISLLeagueChannel : MVC3.SLLeague.ISLLeague, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SLLeagueClient : System.ServiceModel.ClientBase<MVC3.SLLeague.ISLLeague>, MVC3.SLLeague.ISLLeague {
        
        public SLLeagueClient() {
        }
        
        public SLLeagueClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SLLeagueClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLLeagueClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLLeagueClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DomainModel.League GetLeague(int id, ref string[] errors) {
            return base.Channel.GetLeague(id, ref errors);
        }
        
        public void InsertLeague(DomainModel.League league, ref string[] errors) {
            base.Channel.InsertLeague(league, ref errors);
        }
        
        public void UpdateLeague(DomainModel.League league, ref string[] errors) {
            base.Channel.UpdateLeague(league, ref errors);
        }
        
        public void DeleteLeague(int id, ref string[] errors) {
            base.Channel.DeleteLeague(id, ref errors);
        }
        
        public DomainModel.League[] GetLeagueList(ref string[] errors) {
            return base.Channel.GetLeagueList(ref errors);
        }
    }
}
