//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC3.SLPlayer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SLPlayer.ISLPlayer")]
    public interface ISLPlayer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLPlayer/GetPlayer", ReplyAction="http://tempuri.org/ISLPlayer/GetPlayerResponse")]
        DomainModel.Player GetPlayer(int id, ref string[] errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLPlayer/InsertPlayer", ReplyAction="http://tempuri.org/ISLPlayer/InsertPlayerResponse")]
        void InsertPlayer(DomainModel.Player player, ref string[] errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLPlayer/UpdatePlayer", ReplyAction="http://tempuri.org/ISLPlayer/UpdatePlayerResponse")]
        void UpdatePlayer(DomainModel.Player player, ref string[] errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLPlayer/DeletePlayer", ReplyAction="http://tempuri.org/ISLPlayer/DeletePlayerResponse")]
        void DeletePlayer(int id, ref string[] errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLPlayer/GetPlayerList", ReplyAction="http://tempuri.org/ISLPlayer/GetPlayerListResponse")]
        DomainModel.Player[] GetPlayerList(ref string[] errors);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISLPlayerChannel : MVC3.SLPlayer.ISLPlayer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SLPlayerClient : System.ServiceModel.ClientBase<MVC3.SLPlayer.ISLPlayer>, MVC3.SLPlayer.ISLPlayer {
        
        public SLPlayerClient() {
        }
        
        public SLPlayerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SLPlayerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLPlayerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLPlayerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DomainModel.Player GetPlayer(int id, ref string[] errors) {
            return base.Channel.GetPlayer(id, ref errors);
        }
        
        public void InsertPlayer(DomainModel.Player player, ref string[] errors) {
            base.Channel.InsertPlayer(player, ref errors);
        }
        
        public void UpdatePlayer(DomainModel.Player player, ref string[] errors) {
            base.Channel.UpdatePlayer(player, ref errors);
        }
        
        public void DeletePlayer(int id, ref string[] errors) {
            base.Channel.DeletePlayer(id, ref errors);
        }
        
        public DomainModel.Player[] GetPlayerList(ref string[] errors) {
            return base.Channel.GetPlayerList(ref errors);
        }
    }
}
